### ISSUE TITLE
Add keybinds for increasing/decreasing FOV while in-game

### ISSUE THREAD

**Issue by trixnz** [trixnz/justfov#7]
As suggested by the redditor /u/Bongjum: https://www.reddit.com/r/JustCause/comments/3ydhfa/justfov_the_long_awaited_fov_patcher_is_here/cze39a9

**Comment by PsykomantaBrain** [comment]
I've got that set up here in my version, I didn't want to push it because it wasn't working properly without the new offsets, but I'll merge it with the latest commits now that that's working (thanks xforce!)

Keybinds are Numpad / and * to increase/decrease FOV. I'll also see about adding a toggle to revert back to the stock auto-fov, which is still useful if you want to use the sniper rifles and such.

Cheers

**Comment by PsykomantaBrain** [comment]
[There](https://github.com/trixnz/justfov/pull/12). I added keys to tweak and toggle the FOV. Tested to work with the current version of the game on Steam. It doesn't modify the model (much), so future offset tweaks shouldn't be affected by this or vice-versa.

Cheers

**Comment by trixnz** [comment]
Resolved by @PsykomantaBrain's PR: https://github.com/trixnz/justfov/pull/12. Thanks!
